### ISSUE TITLE
git lfs install gives an error

### ISSUE THREAD

**Issue by qboehler** [ethz-msrl/tesla_install#14]
After testing https://github.com/ethz-msrl/tesla_install/pull/13 and carefully looking at possible errors in the terminal, I noticed that this

https://github.com/ethz-msrl/tesla_install/blob/870c061b6ee19fff0133a0232984bddfe7e74190/install.sh#L108

led to the following error

`Error: Failed to call git rev-parse --git-dir: exit status 128 `

followed by the confirmation

`Git LFS initialized.`

From this https://github.com/git-lfs/git-lfs/issues/3964 it seems that it may not be problem. But probably running the command from `src/Tesla` as recommended here https://github.com/ethz-msrl/Tesla/wiki/Installation#large-data-files would avoid the message.

**Comment by samlcharreyron** [comment]
The thing is that `src/Tesla` does not exist yet if this is done on a new machine. I'm going to close this because it seems that this is problem that is fixed in a newer version of git LFS.
