### ISSUE TITLE
pre-commit hook only installed for Tesla

### ISSUE THREAD

**Issue by qboehler** [ethz-msrl/tesla_install#3]
I believe this setup the hook only for Tesla:

https://github.com/ethz-msrl/tesla_install/blob/fe38cf8e0291938829b1194bed17fa2f1a7b739c/install.sh#L122-L123

Shouldn't you also do the same in Tesla_core (see https://github.com/ethz-msrl/Tesla_core/pull/172)?

**Comment by samlcharreyron** [comment]
yes correct. I guess we may want to do this for Navion as well.
